### ISSUE TITLE
Contributor olabilir miyiz?

### ISSUE THREAD

**Issue by OrhanOzkercin** [alperen/training-book-2019#4]
Merhaba, reponuz çok hoş olmuş. Contributors kabul ediyor musunuz? Katkıda bulunabilir miyiz?

**Comment by alperen** [comment]
Merhaba @OrhanOzkercin, tabi ki repo katkiniza aciktir fakat katkida bulunmak istediginiz konuyu belirtmekte fayda var. Cunku halihazirda bitmis bir durumda. Sadece yazilardaki anlam bozukluklarini ve teknik yanlisliklari duzeltebiliriz. Yeni gunler, yeni yazi eklemek, cikarmak vs. gibi seyler uygun olmayacaktir.

**Comment by OrhanOzkercin** [comment]
Merhaba @alperen, çok afedersiniz ben repoyu genel genişletmek isteyebilirsiniz diye düşündüm, staj deneyimin dışında. Kusura bakmayın yanlış anlamışım. Size başarılar diliyorum (:
